export const JLPT_DATA = {
    N5: [
      { kanji: '日', reading: 'にち', meaning: 'ngày' },
      { kanji: '本', reading: 'ほん', meaning: 'sách' },
      { kanji: '人', reading: 'ひと', meaning: 'người' },
      { kanji: '月', reading: 'つき', meaning: 'mặt trăng' },
      { kanji: '火', reading: 'ひ', meaning: 'lửa' },
      { kanji: '水', reading: 'みず', meaning: 'nước' },
      { kanji: '木', reading: 'き', meaning: 'cây' },
      { kanji: '金', reading: 'かね', meaning: 'tiền' },
      { kanji: '土', reading: 'つち', meaning: 'đất' },
      { kanji: '山', reading: 'やま', meaning: 'núi' },
      { kanji: '川', reading: 'かわ', meaning: 'sông' },
      { kanji: '田', reading: 'た', meaning: 'ruộng' },
      { kanji: '目', reading: 'め', meaning: 'mắt' },
      { kanji: '口', reading: 'くち', meaning: 'miệng' },
      { kanji: '手', reading: 'て', meaning: 'tay' },
      { kanji: '足', reading: 'あし', meaning: 'chân' },
      { kanji: '耳', reading: 'みみ', meaning: 'tai' },
      { kanji: '花', reading: 'はな', meaning: 'hoa' },
      { kanji: '雨', reading: 'あめ', meaning: 'mưa' },
      { kanji: '雪', reading: 'ゆき', meaning: 'tuyết' },
      { kanji: '空', reading: 'そら', meaning: 'bầu trời' },
      { kanji: '風', reading: 'かぜ', meaning: 'gió' },
      { kanji: '魚', reading: 'さかな', meaning: 'cá' },
      { kanji: '鳥', reading: 'とり', meaning: 'chim' },
      { kanji: '犬', reading: 'いぬ', meaning: 'chó' },
      { kanji: '猫', reading: 'ねこ', meaning: 'mèo' },
      { kanji: '馬', reading: 'うま', meaning: 'ngựa' },
      { kanji: '牛', reading: 'うし', meaning: 'bò' },
      { kanji: '羊', reading: 'ひつじ', meaning: 'cừu' },
      { kanji: '鶏', reading: 'にわとり', meaning: 'gà' },
      { kanji: '米', reading: 'こめ', meaning: 'gạo' },
      { kanji: '茶', reading: 'ちゃ', meaning: 'trà' },
      { kanji: '酒', reading: 'さけ', meaning: 'rượu' },
      { kanji: '肉', reading: 'にく', meaning: 'thịt' },
      { kanji: '卵', reading: 'たまご', meaning: 'trứng' },
      { kanji: '豆', reading: 'まめ', meaning: 'đậu' },
      { kanji: '菜', reading: 'な', meaning: 'rau' },
      { kanji: '果', reading: 'か', meaning: 'trái cây' },
      { kanji: '竹', reading: 'たけ', meaning: 'tre' },
      { kanji: '石', reading: 'いし', meaning: 'đá' },
      { kanji: '砂', reading: 'すな', meaning: 'cát' },
      { kanji: '星', reading: 'ほし', meaning: 'sao' },
      { kanji: '雲', reading: 'くも', meaning: 'mây' },
      { kanji: '雷', reading: 'かみなり', meaning: 'sấm' },
      { kanji: '電', reading: 'でん', meaning: 'điện' },
      { kanji: '車', reading: 'くるま', meaning: 'xe' },
      { kanji: '船', reading: 'ふね', meaning: 'thuyền' },
      { kanji: '道', reading: 'みち', meaning: 'đường' },
      { kanji: '駅', reading: 'えき', meaning: 'nhà ga' },
      { kanji: '家', reading: 'いえ', meaning: 'nhà' },
      { kanji: '門', reading: 'もん', meaning: 'cổng' },
      { kanji: '室', reading: 'しつ', meaning: 'phòng' },
      { kanji: '庭', reading: 'にわ', meaning: 'sân' },
      { kanji: '池', reading: 'いけ', meaning: 'ao' },
      { kanji: '森', reading: 'もり', meaning: 'rừng' },
      { kanji: '林', reading: 'はやし', meaning: 'rừng nhỏ' },
      { kanji: '草', reading: 'くさ', meaning: 'cỏ' },
      { kanji: '葉', reading: 'は', meaning: 'lá' },
      { kanji: '枝', reading: 'えだ', meaning: 'cành' },
      { kanji: '根', reading: 'ね', meaning: 'rễ' },
      { kanji: '実', reading: 'み', meaning: 'quả' },
      { kanji: '色', reading: 'いろ', meaning: 'màu sắc' },
      { kanji: '赤', reading: 'あか', meaning: 'màu đỏ' },
      { kanji: '青', reading: 'あお', meaning: 'màu xanh' },
      { kanji: '白', reading: 'しろ', meaning: 'màu trắng' },
      { kanji: '黒', reading: 'くろ', meaning: 'màu đen' },
      { kanji: '黄', reading: 'き', meaning: 'màu vàng' },
      { kanji: '春', reading: 'はる', meaning: 'mùa xuân' },
      { kanji: '夏', reading: 'なつ', meaning: 'mùa hè' },
      { kanji: '秋', reading: 'あき', meaning: 'mùa thu' },
      { kanji: '冬', reading: 'ふゆ', meaning: 'mùa đông' },
      { kanji: '朝', reading: 'あさ', meaning: 'buổi sáng' },
      { kanji: '昼', reading: 'ひる', meaning: 'buổi trưa' },
      { kanji: '夜', reading: 'よる', meaning: 'buổi tối' },
      { kanji: '時', reading: 'とき', meaning: 'thời gian' },
      { kanji: '分', reading: 'ふん', meaning: 'phút' },
      { kanji: '年', reading: 'とし', meaning: 'năm' },
      { kanji: '週', reading: 'しゅう', meaning: 'tuần' },
      { kanji: '曜', reading: 'よう', meaning: 'thứ' },
      { kanji: '午', reading: 'ご', meaning: 'trưa' },
      { kanji: '前', reading: 'まえ', meaning: 'trước' },
      { kanji: '後', reading: 'あと', meaning: 'sau' },
      { kanji: '内', reading: 'うち', meaning: 'trong' },
      { kanji: '外', reading: 'そと', meaning: 'ngoài' },
      { kanji: '北', reading: 'きた', meaning: 'bắc' },
      { kanji: '南', reading: 'みなみ', meaning: 'nam' },
      { kanji: '東', reading: 'ひがし', meaning: 'đông' },
      { kanji: '西', reading: 'にし', meaning: 'tây' },
      { kanji: '上', reading: 'うえ', meaning: 'trên' },
      { kanji: '下', reading: 'した', meaning: 'dưới' },
      { kanji: '中', reading: 'なか', meaning: 'giữa' },
      { kanji: '右', reading: 'みぎ', meaning: 'phải' },
      { kanji: '左', reading: 'ひだり', meaning: 'trái' },
      { kanji: '父', reading: 'ちち', meaning: 'bố' },
      { kanji: '母', reading: 'はは', meaning: 'mẹ' },
      { kanji: '子', reading: 'こ', meaning: 'con' },
      { kanji: '男', reading: 'おとこ', meaning: 'nam' },
      { kanji: '女', reading: 'おんな', meaning: 'nữ' },
      { kanji: '友', reading: 'とも', meaning: 'bạn' },
      { kanji: '名', reading: 'な', meaning: 'tên' },
      { kanji: '字', reading: 'じ', meaning: 'chữ' },
      { kanji: '文', reading: 'ぶん', meaning: 'văn' },
      { kanji: '学', reading: 'がく', meaning: 'học' },
      { kanji: '校', reading: 'こう', meaning: 'trường' },
      { kanji: '生', reading: 'せい', meaning: 'sinh' },
      { kanji: '先', reading: 'せん', meaning: 'trước' }
    ],
    N4: [
      { kanji: '同', reading: 'おなじ', meaning: 'giống nhau' },
      { kanji: '会', reading: 'かい', meaning: 'gặp gỡ' },
      { kanji: '多', reading: 'おおい', meaning: 'nhiều' },
      { kanji: '毎', reading: 'まい', meaning: 'mỗi' },
      { kanji: '親', reading: 'おや', meaning: 'cha mẹ' },
      { kanji: '色', reading: 'いろ', meaning: 'màu sắc' },
      { kanji: '走', reading: 'はしる', meaning: 'chạy' },
      { kanji: '止', reading: 'とまる', meaning: 'dừng lại' },
      { kanji: '楽', reading: 'たのしい', meaning: 'vui vẻ' },
      { kanji: '働', reading: 'はたらく', meaning: 'làm việc' },
      { kanji: '考', reading: 'かんがえる', meaning: 'suy nghĩ' },
      { kanji: '思', reading: 'おもう', meaning: 'nghĩ' },
      { kanji: '知', reading: 'しる', meaning: 'biết' },
      { kanji: '使', reading: 'つかう', meaning: 'sử dụng' },
      { kanji: '始', reading: 'はじめる', meaning: 'bắt đầu' },
      { kanji: '終', reading: 'おわる', meaning: 'kết thúc' },
      { kanji: '持', reading: 'もつ', meaning: 'cầm, giữ' },
      { kanji: '待', reading: 'まつ', meaning: 'đợi' },
      { kanji: '急', reading: 'いそぐ', meaning: 'vội vàng' },
      { kanji: '決', reading: 'きめる', meaning: 'quyết định' },
      { kanji: '和', reading: 'わ', meaning: 'hòa bình' },
      { kanji: '英', reading: 'えい', meaning: 'Anh' },
      { kanji: '語', reading: 'ご', meaning: 'ngôn ngữ' },
      { kanji: '数', reading: 'かず', meaning: 'số' },
      { kanji: '理', reading: 'り', meaning: 'lý' },
      { kanji: '科', reading: 'か', meaning: 'khoa' },
      { kanji: '算', reading: 'さん', meaning: 'tính' },
      { kanji: '歌', reading: 'うた', meaning: 'bài hát' },
      { kanji: '絵', reading: 'え', meaning: 'tranh' },
      { kanji: '図', reading: 'ず', meaning: 'hình' },
      { kanji: '工', reading: 'こう', meaning: 'công' },
      { kanji: '場', reading: 'ば', meaning: 'trường' },
      { kanji: '業', reading: 'ぎょう', meaning: 'nghiệp' },
      { kanji: '員', reading: 'いん', meaning: 'viên' },
      { kanji: '売', reading: 'う', meaning: 'bán' },
      { kanji: '買', reading: 'か', meaning: 'mua' },
      { kanji: '安', reading: 'やす', meaning: 'rẻ' },
      { kanji: '高', reading: 'たか', meaning: 'cao' },
      { kanji: '低', reading: 'ひく', meaning: 'thấp' },
      { kanji: '新', reading: 'しん', meaning: 'mới' },
      { kanji: '古', reading: 'ふる', meaning: 'cũ' },
      { kanji: '良', reading: 'よ', meaning: 'tốt' },
      { kanji: '悪', reading: 'わる', meaning: 'xấu' },
      { kanji: '強', reading: 'つよ', meaning: 'mạnh' },
      { kanji: '弱', reading: 'よわ', meaning: 'yếu' },
      { kanji: '早', reading: 'はや', meaning: 'sớm' },
      { kanji: '遅', reading: 'おそ', meaning: 'muộn' },
      { kanji: '近', reading: 'ちか', meaning: 'gần' },
      { kanji: '遠', reading: 'とお', meaning: 'xa' },
      { kanji: '軽', reading: 'かる', meaning: 'nhẹ' },
      { kanji: '重', reading: 'おも', meaning: 'nặng' },
      { kanji: '暑', reading: 'あつ', meaning: 'nóng' },
      { kanji: '寒', reading: 'さむ', meaning: 'lạnh' },
      { kanji: '暖', reading: 'あたた', meaning: 'ấm' },
      { kanji: '涼', reading: 'すず', meaning: 'mát' },
      { kanji: '明', reading: 'あか', meaning: 'sáng' },
      { kanji: '暗', reading: 'くら', meaning: 'tối' },
      { kanji: '太', reading: 'ふと', meaning: 'béo' },
      { kanji: '細', reading: 'ほそ', meaning: 'gầy' },
      { kanji: '広', reading: 'ひろ', meaning: 'rộng' },
      { kanji: '狭', reading: 'せま', meaning: 'hẹp' },
      { kanji: '深', reading: 'ふか', meaning: 'sâu' },
      { kanji: '浅', reading: 'あさ', meaning: 'nông' },
      { kanji: '長', reading: 'なが', meaning: 'dài' },
      { kanji: '短', reading: 'みじか', meaning: 'ngắn' },
      { kanji: '丸', reading: 'まる', meaning: 'tròn' },
      { kanji: '角', reading: 'かく', meaning: 'góc' },
      { kanji: '直', reading: 'ちょく', meaning: 'thẳng' },
      { kanji: '曲', reading: 'まが', meaning: 'cong' },
      { kanji: '平', reading: 'たい', meaning: 'phẳng' },
      { kanji: '若', reading: 'わか', meaning: 'trẻ' },
      { kanji: '老', reading: 'ろう', meaning: 'già' },
      { kanji: '死', reading: 'し', meaning: 'chết' },
      { kanji: '病', reading: 'びょう', meaning: 'bệnh' },
      { kanji: '元', reading: 'げん', meaning: 'nguyên' },
      { kanji: '気', reading: 'き', meaning: 'khí' },
      { kanji: '天', reading: 'てん', meaning: 'trời' },
      { kanji: '地', reading: 'ち', meaning: 'đất' },
      { kanji: '海', reading: 'うみ', meaning: 'biển' },
      { kanji: '洋', reading: 'よう', meaning: 'đại dương' },
      { kanji: '島', reading: 'しま', meaning: 'đảo' },
      { kanji: '岩', reading: 'いわ', meaning: 'đá' },
      { kanji: '波', reading: 'なみ', meaning: 'sóng' },
      { kanji: '音', reading: 'おと', meaning: 'âm thanh' },
      { kanji: '声', reading: 'こえ', meaning: 'giọng nói' },
      { kanji: '光', reading: 'ひかり', meaning: 'ánh sáng' },
      { kanji: '影', reading: 'かげ', meaning: 'bóng' },
      { kanji: '形', reading: 'かたち', meaning: 'hình dạng' },
      { kanji: '線', reading: 'せん', meaning: 'đường' },
      { kanji: '点', reading: 'てん', meaning: 'điểm' },
      { kanji: '丁', reading: 'ちょう', meaning: 'khối' },
      { kanji: '半', reading: 'はん', meaning: 'nửa' },
      { kanji: '百', reading: 'ひゃく', meaning: 'trăm' },
      { kanji: '千', reading: 'せん', meaning: 'nghìn' },
      { kanji: '万', reading: 'まん', meaning: 'vạn' },
      { kanji: '円', reading: 'えん', meaning: 'yên' },
      { kanji: '市', reading: 'し', meaning: 'thành phố' },
      { kanji: '区', reading: 'く', meaning: 'quận' },
      { kanji: '町', reading: 'まち', meaning: 'phố' },
      { kanji: '村', reading: 'むら', meaning: 'làng' },
      { kanji: '都', reading: 'と', meaning: 'đô' },
      { kanji: '府', reading: 'ふ', meaning: 'phủ' },
      { kanji: '県', reading: 'けん', meaning: 'tỉnh' },
      { kanji: '国', reading: 'くに', meaning: 'quốc gia' },
      { kanji: '世', reading: 'せ', meaning: 'thế giới' },
      { kanji: '界', reading: 'かい', meaning: 'giới' }
    ],
    N3: [
      { kanji: '政', reading: 'せい', meaning: 'chính trị' },
      { kanji: '経', reading: 'けい', meaning: 'kinh tế' },
      { kanji: '際', reading: 'さい', meaning: 'dịp, khi' },
      { kanji: '配', reading: 'くばる', meaning: 'phân phối' },
      { kanji: '席', reading: 'せき', meaning: 'chỗ ngồi' },
      { kanji: '残', reading: 'のこる', meaning: 'còn lại' },
      { kanji: '能', reading: 'のう', meaning: 'khả năng' },
      { kanji: '術', reading: 'じゅつ', meaning: 'kỹ thuật' },
      { kanji: '格', reading: 'かく', meaning: 'địa vị' },
      { kanji: '優', reading: 'やさしい', meaning: 'tốt, ưu tú' },
      { kanji: '限', reading: 'かぎる', meaning: 'giới hạn' },
      { kanji: '望', reading: 'のぞむ', meaning: 'hy vọng' },
      { kanji: '確', reading: 'たしか', meaning: 'chắc chắn' },
      { kanji: '認', reading: 'みとめる', meaning: 'công nhận' },
      { kanji: '察', reading: 'さつ', meaning: 'quan sát' },
      { kanji: '情', reading: 'じょう', meaning: 'tình cảm' },
      { kanji: '構', reading: 'かまう', meaning: 'cấu trúc' },
      { kanji: '解', reading: 'かい', meaning: 'hiểu' },
      { kanji: '論', reading: 'ろん', meaning: 'lý luận' },
      { kanji: '難', reading: 'むずかしい', meaning: 'khó' },
      { kanji: '企', reading: 'き', meaning: 'kế hoạch' },
      { kanji: '義', reading: 'ぎ', meaning: 'nghĩa' },
      { kanji: '課', reading: 'か', meaning: 'khóa' },
      { kanji: '選', reading: 'せん', meaning: 'chọn' },
      { kanji: '挙', reading: 'きょ', meaning: 'cử' },
      { kanji: '資', reading: 'し', meaning: 'tư' },
      { kanji: '準', reading: 'じゅん', meaning: 'chuẩn' },
      { kanji: '備', reading: 'び', meaning: 'bị' },
      { kanji: '保', reading: 'ほ', meaning: 'bảo' },
      { kanji: '険', reading: 'けん', meaning: 'hiểm' },
      { kanji: '査', reading: 'さ', meaning: 'tra' },
      { kanji: '証', reading: 'しょう', meaning: 'chứng' },
      { kanji: '評', reading: 'ひょう', meaning: 'đánh giá' },
      { kanji: '判', reading: 'はん', meaning: 'phán' },
      { kanji: '制', reading: 'せい', meaning: 'chế' },
      { kanji: '務', reading: 'む', meaning: 'vụ' },
      { kanji: '設', reading: 'せつ', meaning: 'thiết' },
      { kanji: '規', reading: 'き', meaning: 'quy' },
      { kanji: '則', reading: 'そく', meaning: 'tắc' },
      { kanji: '衛', reading: 'えい', meaning: 'vệ' },
      { kanji: '張', reading: 'ちょう', meaning: 'trương' },
      { kanji: '違', reading: 'い', meaning: 'vi' },
      { kanji: '反', reading: 'はん', meaning: 'phản' },
      { kanji: '質', reading: 'しつ', meaning: 'chất' },
      { kanji: '供', reading: 'きょう', meaning: 'cung' },
      { kanji: '与', reading: 'よ', meaning: 'dữ' },
      { kanji: '需', reading: 'じゅ', meaning: 'nhu' },
      { kanji: '応', reading: 'おう', meaning: 'ứng' },
      { kanji: '援', reading: 'えん', meaning: 'viện' },
      { kanji: '助', reading: 'じょ', meaning: 'trợ' },
      { kanji: '協', reading: 'きょう', meaning: 'hiệp' },
      { kanji: '調', reading: 'ちょう', meaning: 'điều' },
      { kanji: '査', reading: 'さ', meaning: 'tra' },
      { kanji: '報', reading: 'ほう', meaning: 'báo' },
      { kanji: '告', reading: 'こく', meaning: 'cáo' },
      { kanji: '示', reading: 'じ', meaning: 'thị' },
      { kanji: '達', reading: 'たつ', meaning: 'đạt' },
      { kanji: '成', reading: 'せい', meaning: 'thành' },
      { kanji: '績', reading: 'せき', meaning: 'tích' },
      { kanji: '結', reading: 'けつ', meaning: 'kết' },
      { kanji: '果', reading: 'か', meaning: 'quả' },
      { kanji: '続', reading: 'ぞく', meaning: 'tục' },
      { kanji: '増', reading: 'ぞう', meaning: 'tăng' },
      { kanji: '減', reading: 'げん', meaning: 'giảm' },
      { kanji: '加', reading: 'か', meaning: 'gia' },
      { kanji: '除', reading: 'じょ', meaning: 'trừ' },
      { kanji: '変', reading: 'へん', meaning: 'biến' },
      { kanji: '更', reading: 'こう', meaning: 'canh' },
      { kanji: '改', reading: 'かい', meaning: 'cải' },
      { kanji: '良', reading: 'りょう', meaning: 'lương' },
      { kanji: '好', reading: 'こう', meaning: 'hảo' },
      { kanji: '適', reading: 'てき', meaning: 'thích' },
      { kanji: '当', reading: 'とう', meaning: 'đương' },
      { kanji: '向', reading: 'こう', meaning: 'hướng' },
      { kanji: '応', reading: 'おう', meaning: 'ứng' },
      { kanji: '対', reading: 'たい', meaning: 'đối' },
      { kanji: '比', reading: 'ひ', meaning: 'tỷ' },
      { kanji: '較', reading: 'かく', meaning: 'giác' },
      { kanji: '類', reading: 'るい', meaning: 'loại' },
      { kanji: '似', reading: 'に', meaning: 'tự' },
      { kanji: '違', reading: 'い', meaning: 'vi' },
      { kanji: '異', reading: 'い', meaning: 'dị' },
      { kanji: '差', reading: 'さ', meaning: 'sai' },
      { kanji: '別', reading: 'べつ', meaning: 'biệt' },
      { kanji: '特', reading: 'とく', meaning: 'đặc' },
      { kanji: '殊', reading: 'しゅ', meaning: 'thù' },
      { kanji: '他', reading: 'た', meaning: 'tha' },
      { kanji: '共', reading: 'きょう', meaning: 'cộng' },
      { kanji: '総', reading: 'そう', meaning: 'tổng' },
      { kanji: '各', reading: 'かく', meaning: 'các' },
      { kanji: '個', reading: 'こ', meaning: 'cá' },
      { kanji: '別', reading: 'べつ', meaning: 'biệt' },
      { kanji: '全', reading: 'ぜん', meaning: 'toàn' },
      { kanji: '部', reading: 'ぶ', meaning: 'bộ' },
      { kanji: '分', reading: 'ぶん', meaning: 'phần' },
      { kanji: '区', reading: 'く', meaning: 'khu' },
      { kanji: '域', reading: 'いき', meaning: 'vực' },
      { kanji: '所', reading: 'しょ', meaning: 'sở' },
      { kanji: '属', reading: 'ぞく', meaning: 'thuộc' },
      { kanji: '系', reading: 'けい', meaning: 'hệ' },
      { kanji: '統', reading: 'とう', meaning: 'thống' },
      { kanji: '管', reading: 'かん', meaning: 'quản' },
      { kanji: '轄', reading: 'かつ', meaning: 'hạt' },
      { kanji: '率', reading: 'りつ', meaning: 'suất' },
      { kanji: '割', reading: 'わり', meaning: 'cát' },
      { kanji: '合', reading: 'ごう', meaning: 'hợp' },
      { kanji: '数', reading: 'すう', meaning: 'số' }
    ],
    N2: [
      { kanji: '批', reading: 'ひ', meaning: 'phê bình' },
      { kanji: '判', reading: 'はん', meaning: 'phán đoán' },
      { kanji: '認', reading: 'にん', meaning: 'công nhận' },
      { kanji: '論', reading: 'ろん', meaning: 'lý luận' },
      { kanji: '革', reading: 'かく', meaning: 'cách mạng' },
      { kanji: '障', reading: 'しょう', meaning: 'chướng ngại' },
      { kanji: '域', reading: 'いき', meaning: 'khu vực' },
      { kanji: '密', reading: 'みつ', meaning: 'bí mật' },
      { kanji: '我', reading: 'が', meaning: 'tôi' },
      { kanji: '故', reading: 'ゆえ', meaning: 'lý do' },
      { kanji: '績', reading: 'せき', meaning: 'thành tích' },
      { kanji: '徴', reading: 'ちょう', meaning: 'triệu chứng' },
      { kanji: '懸', reading: 'けん', meaning: 'treo' },
      { kanji: '双', reading: 'そう', meaning: 'đôi' },
      { kanji: '刺', reading: 'し', meaning: 'đâm' },
      { kanji: '到', reading: 'とう', meaning: 'đến' },
      { kanji: '宣', reading: 'せん', meaning: 'tuyên bố' },
      { kanji: '尊', reading: 'そん', meaning: 'tôn kính' },
      { kanji: '就', reading: 'しゅう', meaning: 'về việc' },
      { kanji: '層', reading: 'そう', meaning: 'tầng lớp' },
      { kanji: '派', reading: 'は', meaning: 'phái' },
      { kanji: '系', reading: 'けい', meaning: 'hệ thống' },
      { kanji: '承', reading: 'しょう', meaning: 'thừa nhận' },
      { kanji: '統', reading: 'とう', meaning: 'thống nhất' },
      { kanji: '率', reading: 'りつ', meaning: 'tỷ lệ' },
      { kanji: '属', reading: 'ぞく', meaning: 'thuộc về' },
      { kanji: '群', reading: 'ぐん', meaning: 'nhóm' },
      { kanji: '衆', reading: 'しゅう', meaning: 'đám đông' },
      { kanji: '単', reading: 'たん', meaning: 'đơn' },
      { kanji: '独', reading: 'どく', meaning: 'độc lập' },
      { kanji: '裁', reading: 'さい', meaning: 'phán xét' },
      { kanji: '判', reading: 'はん', meaning: 'quyết định' },
      { kanji: '制', reading: 'せい', meaning: 'chế độ' },
      { kanji: '務', reading: 'む', meaning: 'nhiệm vụ' },
      { kanji: '規', reading: 'き', meaning: 'quy tắc' },
      { kanji: '則', reading: 'そく', meaning: 'nguyên tắc' },
      { kanji: '衛', reading: 'えい', meaning: 'bảo vệ' },
      { kanji: '張', reading: 'ちょう', meaning: 'căng ra' },
      { kanji: '違', reading: 'い', meaning: 'khác biệt' },
      { kanji: '犯', reading: 'はん', meaning: 'phạm tội' },
      { kanji: '厳', reading: 'げん', meaning: 'nghiêm khắc' },
      { kanji: '密', reading: 'みつ', meaning: 'bí mật' },
      { kanji: '警', reading: 'けい', meaning: 'cảnh báo' },
      { kanji: '防', reading: 'ぼう', meaning: 'phòng ngừa' },
      { kanji: '守', reading: 'しゅ', meaning: 'bảo vệ' },
      { kanji: '護', reading: 'ご', meaning: 'hộ vệ' },
      { kanji: '監', reading: 'かん', meaning: 'giám sát' },
      { kanji: '督', reading: 'とく', meaning: 'đốc thúc' },
      { kanji: '責', reading: 'せき', meaning: 'trách nhiệm' },
      { kanji: '任', reading: 'にん', meaning: 'nhiệm vụ' },
      { kanji: '権', reading: 'けん', meaning: 'quyền hạn' },
      { kanji: '限', reading: 'げん', meaning: 'giới hạn' },
      { kanji: '能', reading: 'のう', meaning: 'năng lực' },
      { kanji: '可', reading: 'か', meaning: 'có thể' },
      { kanji: '許', reading: 'きょ', meaning: 'cho phép' },
      { kanji: '認', reading: 'にん', meaning: 'thừa nhận' },
      { kanji: '承', reading: 'しょう', meaning: 'chấp nhận' },
      { kanji: '証', reading: 'しょう', meaning: 'chứng nhận' },
      { kanji: '明', reading: 'めい', meaning: 'sáng tỏ' },
      { kanji: '確', reading: 'かく', meaning: 'xác nhận' },
      { kanji: '実', reading: 'じつ', meaning: 'thực tế' },
      { kanji: '施', reading: 'し', meaning: 'thi hành' },
      { kanji: '設', reading: 'せつ', meaning: 'thiết lập' },
      { kanji: '備', reading: 'び', meaning: 'chuẩn bị' },
      { kanji: '製', reading: 'せい', meaning: 'sản xuất' },
      { kanji: '造', reading: 'ぞう', meaning: 'chế tạo' },
      { kanji: '技', reading: 'ぎ', meaning: 'kỹ thuật' },
      { kanji: '術', reading: 'じゅつ', meaning: 'thuật' },
      { kanji: '巧', reading: 'こう', meaning: 'khéo léo' },
      { kanji: '芸', reading: 'げい', meaning: 'nghệ thuật' },
      { kanji: '能', reading: 'のう', meaning: 'tài năng' },
      { kanji: '才', reading: 'さい', meaning: 'tài' },
      { kanji: '腕', reading: 'うで', meaning: 'tay nghề' },
      { kanji: '器', reading: 'き', meaning: 'dụng cụ' },
      { kanji: '械', reading: 'かい', meaning: 'máy móc' },
      { kanji: '機', reading: 'き', meaning: 'máy' },
      { kanji: '材', reading: 'ざい', meaning: 'vật liệu' },
      { kanji: '質', reading: 'しつ', meaning: 'chất lượng' },
      { kanji: '量', reading: 'りょう', meaning: 'số lượng' },
      { kanji: '価', reading: 'か', meaning: 'giá trị' },
      { kanji: '値', reading: 'ち', meaning: 'giá cả' },
      { kanji: '額', reading: 'がく', meaning: 'số tiền' },
      { kanji: '費', reading: 'ひ', meaning: 'phí tổn' },
      { kanji: '用', reading: 'よう', meaning: 'sử dụng' },
      { kanji: '益', reading: 'えき', meaning: 'lợi ích' },
      { kanji: '利', reading: 'り', meaning: 'lợi' },
      { kanji: '損', reading: 'そん', meaning: 'tổn thất' },
      { kanji: '失', reading: 'しつ', meaning: 'mất' },
      { kanji: '得', reading: 'とく', meaning: 'được' },
      { kanji: '収', reading: 'しゅう', meaning: 'thu' },
      { kanji: '支', reading: 'し', meaning: 'chi' },
      { kanji: '払', reading: 'はら', meaning: 'trả' },
      { kanji: '給', reading: 'きゅう', meaning: 'cấp' },
      { kanji: '与', reading: 'よ', meaning: 'cho' },
      { kanji: '課', reading: 'か', meaning: 'khóa' },
      { kanji: '税', reading: 'ぜい', meaning: 'thuế' },
      { kanji: '負', reading: 'ふ', meaning: 'gánh' },
      { kanji: '担', reading: 'たん', meaning: 'đảm' },
      { kanji: '保', reading: 'ほ', meaning: 'bảo' },
      { kanji: '証', reading: 'しょう', meaning: 'chứng' },
      { kanji: '険', reading: 'けん', meaning: 'hiểm' },
      { kanji: '危', reading: 'き', meaning: 'nguy' },
      { kanji: '害', reading: 'がい', meaning: 'hại' },
      { kanji: '傷', reading: 'しょう', meaning: 'thương' },
      { kanji: '損', reading: 'そん', meaning: 'tổn' },
      { kanji: '壊', reading: 'かい', meaning: 'hoại' },
      { kanji: '破', reading: 'は', meaning: 'phá' },
      { kanji: '滅', reading: 'めつ', meaning: 'diệt' }
    ],
    N1: [
      { kanji: '憂', reading: 'うれい', meaning: 'lo lắng' },
      { kanji: '鬱', reading: 'うつ', meaning: 'trầm cảm' },
      { kanji: '璧', reading: 'へき', meaning: 'hoàn hảo' },
      { kanji: '瞭', reading: 'りょう', meaning: 'rõ ràng' },
      { kanji: '麗', reading: 'れい', meaning: 'đẹp đẽ' },
      { kanji: '箋', reading: 'せん', meaning: 'giấy viết thư' },
      { kanji: '籠', reading: 'かご', meaning: 'giỏ' },
      { kanji: '艦', reading: 'かん', meaning: 'tàu chiến' },
      { kanji: '闘', reading: 'とう', meaning: 'chiến đấu' },
      { kanji: '騰', reading: 'とう', meaning: 'tăng lên' },
      { kanji: '藤', reading: 'ふじ', meaning: 'cây tử đằng' },
      { kanji: '襲', reading: 'しゅう', meaning: 'tấn công' },
      { kanji: '贈', reading: 'ぞう', meaning: 'tặng' },
      { kanji: '醸', reading: 'じょう', meaning: 'ủ rượu' },
      { kanji: '弊', reading: 'へい', meaning: 'tệ hại' },
      { kanji: '璃', reading: 'り', meaning: 'thủy tinh' },
      { kanji: '嚇', reading: 'かく', meaning: 'đe dọa' },
      { kanji: '濫', reading: 'らん', meaning: 'tràn lan' },
      { kanji: '癒', reading: 'ゆ', meaning: 'chữa lành' },
      { kanji: '謳', reading: 'おう', meaning: 'ca ngợi' }
    ]
  };
  
  export const EXAMPLE_SENTENCES = {
    '日': [
      {
        japanese: '今日はいい日です。',
        english: 'Today is a good day.',
        romaji: 'Kyō wa ii hi desu.'
      },
      {
        japanese: '日本語を勉強しています。',
        english: 'I am studying Japanese.',
        romaji: 'Nihongo o benkyō shite imasu.'
      }
    ],
    '本': [
      {
        japanese: 'この本は面白いです。',
        english: 'This book is interesting.',
        romaji: 'Kono hon wa omoshiroi desu.'
      },
      {
        japanese: '本を読むのが好きです。',
        english: 'I like reading books.',
        romaji: 'Hon o yomu no ga suki desu.'
      }
    ]
  };
  
  export const POPULAR_WORDS = [
    { word: '猫', reading: 'ねこ', meaning: 'cat' },
    { word: '犬', reading: 'いぬ', meaning: 'dog' },
    { word: '水', reading: 'みず', meaning: 'water' },
    { word: '火', reading: 'ひ', meaning: 'fire' },
    { word: '山', reading: 'やま', meaning: 'mountain' },
    { word: '川', reading: 'かわ', meaning: 'river' },
    { word: '空', reading: 'そら', meaning: 'sky' },
    { word: '雨', reading: 'あめ', meaning: 'rain' },
    { word: '雪', reading: 'ゆき', meaning: 'snow' },
    { word: '風', reading: 'かぜ', meaning: 'wind' },
    { word: '花', reading: 'はな', meaning: 'flower' },
    { word: '木', reading: 'き', meaning: 'tree' }
  ];


  export const ANALYTICS_DATA = {
    dailySearches: [
      { date: 'Mon', searches: 1850 },
      { date: 'Tue', searches: 2750 },
      { date: 'Wed', searches: 2100 },
      { date: 'Thu', searches: 3200 },
      { date: 'Fri', searches: 2600 },
      { date: 'Sat', searches: 3400 },
      { date: 'Sun', searches: 2900 }
    ],
    mostSearchedKanji: [
      { kanji: '愛', searches: 245 },
      { kanji: '食', searches: 210 },
      { kanji: '水', searches: 185 },
      { kanji: '私', searches: 150 },
      { kanji: '人', searches: 125 }
    ],
    userStatistics: {
      newUsersToday: 24,
      activeUsers: 1245,
      totalSearches: 45678,
      averageSessionTime: '4m 32s'
    }
  };


  export const WORDS_DATA = {
    N5: [
      { word: '言葉', reading: 'ことば', meaning: 'word; language', example: '日本語の言葉を勉強します。' },
      { word: '辞書', reading: 'じしょ', meaning: 'dictionary', example: '辞書で単語を調べます。' },
      { word: '勉強', reading: 'べんきょう', meaning: 'study', example: '毎日日本語を勉強します。' },
      { word: '学校', reading: 'がっこう', meaning: 'school', example: '学校に行きます。' },
      { word: '先生', reading: 'せんせい', meaning: 'teacher', example: '田中先生は親切です。' }
    ],
    N4: [
      { word: '練習', reading: 'れんしゅう', meaning: 'practice', example: '漢字の練習をします。' },
      { word: '意味', reading: 'いみ', meaning: 'meaning', example: 'この言葉の意味を教えてください。' },
      { word: '文法', reading: 'ぶんぽう', meaning: 'grammar', example: '日本語の文法は難しいです。' },
      { word: '発音', reading: 'はつおん', meaning: 'pronunciation', example: 'この発音は難しいです。' },
      { word: '単語', reading: 'たんご', meaning: 'vocabulary', example: '新しい単語を覚えます。' }
    ],
    N3: [
      { word: '表現', reading: 'ひょうげん', meaning: 'expression', example: 'この表現はよく使います。' },
      { word: '文章', reading: 'ぶんしょう', meaning: 'sentence, text', example: '長い文章を書きます。' },
      { word: '会話', reading: 'かいわ', meaning: 'conversation', example: '日本語で会話をします。' },
      { word: '翻訳', reading: 'ほんやく', meaning: 'translation', example: '英語から日本語に翻訳します。' },
      { word: '語彙', reading: 'ごい', meaning: 'vocabulary', example: '語彙力を高めます。' }
    ],
    N2: [
      { word: '熟語', reading: 'じゅくご', meaning: 'idiom, compound word', example: '新しい熟語を学びます。' },
      { word: '敬語', reading: 'けいご', meaning: 'honorific language', example: '敬語を使って話します。' },
      { word: '方言', reading: 'ほうげん', meaning: 'dialect', example: '関西の方言を勉強します。' },
      { word: '語源', reading: 'ごげん', meaning: 'word origin', example: 'この言葉の語源を調べます。' },
      { word: '慣用句', reading: 'かんようく', meaning: 'idiomatic expression', example: '日本語の慣用句を覚えます。' }
    ],
    N1: [
      { word: '語感', reading: 'ごかん', meaning: 'language intuition', example: '日本語の語感を身につけます。' },
      { word: '語調', reading: 'ごちょう', meaning: 'tone of speech', example: '優しい語調で話します。' },
      { word: '語義', reading: 'ごぎ', meaning: 'word meaning', example: '語義を正確に理解します。' },
      { word: '語法', reading: 'ごほう', meaning: 'usage, grammar', example: '正しい語法を学びます。' },
      { word: '語用', reading: 'ごよう', meaning: 'pragmatics', example: '語用論を研究します。' }
    ]
  };